import {
  addTask,
  chat,
  completeTask,
  directoryReader,
  editNoteByManager,
  fileReader,
  internalChatForManager,
  leaveNoteFromManager,
  listNotes,
  listTasks,
  readNote,
  readTask,
  removeNote,
  searchInFolder,
  searchInFile,
  updateTask,
} from 'tools/index';

export const tools = [
  addTask,
  chat,
  completeTask,
  directoryReader,
  editNoteByManager,
  fileReader,
  internalChatForManager,
  leaveNoteFromManager,
  listNotes,
  listTasks,
  readNote,
  readTask,
  removeNote,
  searchInFolder,
  searchInFile,
  updateTask,
];
